spring.application.name=taskmanagement

# Server Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://127.0.0.1/task-management
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret Key
jwt.secret=MySuperSecretKeyMySuperSecretKey12345678
jwt.expiration=86400000  # 1 day

logging.level.root=INFO

# Enable Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics

# Show detailed health status
management.endpoint.health.show-details=always

# Set base path for Actuator
management.endpoints.web.base-path=/actuator
management.endpoint.health.probes.enabled=true